# Generated by Django 5.2.4 on 2025-07-23 22:24

import apps.review.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasification', '0001_initial'),
        ('review', '0002_plataforms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('card_image', models.ImageField(default='review/default/review_default.png', upload_to=apps.review.models.get_card_image_filename)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='clasification.category')),
                ('plataform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='clasification.plataform')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Plataforms',
        ),
    ]
